version: '3.3'

services:
    smee:
        container_name: smee
        dns: 10.3.1.4
        dns_search:
            - ubuntu.home
            - home
        environment:
            SMEE_URL: https://smee.io/Zvo5ZZlapyJTW8Q9
            SMEE_TARGET: https://s5.ubuntu.home:16443
        hostname: smee.home
        image: ${DOCKER_REGISTRY:-ubuntu-s2.home:5000/}${CONTAINER_OS:-alpine}/smee:${CONTAINER_TAG:-ff533a242843074b4fb7348f6f9120a8a0e2140c08f7a3b3dd1e3b1bae15ee13}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        restart: unless-stopped               # only use when building a 'service container'
