version: '3.3'

services:
    smee:
        container_name: smee
        environment:
            SMEE_PROXY: /jenkins
            SMEE_TARGET: https://ubuntu-s3/
            SMEE_URL: https://smee.io/F9gFiEeTza0Po4Rd
        hostname: smee
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/smee:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
